"use strict";
/* -------------------------------------
		CUSTOM FUNCTION WRITE HERE
-------------------------------------- */

"use strict";$(document).ready(function(){$(".sticky-1, .sticky-2").sticky({topSpacing:0});$(window).scroll(function(){if($(this).scrollTop()>1000){$('#scrollup').fadeIn()}else{$('#scrollup').fadeOut()}});$('#scrollup').on('click',function(){$("html, body").animate({scrollTop:0},1000);return!1});var setElementHeight=function(){var width=$(window).width();var height=$(window).height();$('.fullscreen').css('height',(height))}
$(window).resize(function(){setElementHeight()}).resize();$('#banner-slider').owlCarousel({animateOut:'fadeOut',autoplay:!0,items:1,nav:!1,loop:!0,dots:!1,smartSpeed:450});$('.enquiry-form-holder .bars-icon').on('click',function(){$('.enquiry-form-holder').toggleClass("in-hieght")});var wow=new WOW({boxClass:'animate',animateClass:'animated',offset:100,mobile:!1});wow.init();$('#slider-post').owlCarousel({items:1,nav:!0,loop:!0,dots:!1,smartSpeed:450});$('a[href="#search"]').on('click',function(event){event.preventDefault();$('#search').addClass('open');$('#search > form > input[type="search"]').focus()});$('#search, #search button.close').on('click',function(event){if(event.target==this||event.target.className=='close'||event.keyCode==27){$(this).removeClass('open')}});$('.chose-color').colorpicker();$('#services-slider').owlCarousel({loop:!0,margin:30,nav:!0,dots:!1,smartSpeed:200,responsiveClass:!0,responsive:{0:{items:1},320:{items:1},480:{items:1},640:{items:2},768:{items:2},800:{items:2},960:{items:2},991:{items:2},1024:{items:3},1199:{items:3}}})
$('.service-v2-slider').owlCarousel({loop:!0,margin:30,nav:!1,dots:!1,smartSpeed:200,responsiveClass:!0,responsive:{0:{items:1},320:{items:1},480:{items:1},640:{items:2},768:{items:2},800:{items:2},960:{items:3},991:{items:3},1024:{items:4},1199:{items:4}}})
$('#brand-icons-slider').owlCarousel({loop:!0,margin:30,nav:!1,dots:!1,autoplay:!0,smartSpeed:200,responsiveClass:!0,responsive:{0:{items:1},320:{items:1},480:{items:2},640:{items:2},768:{items:3},800:{items:4},960:{items:4},1200:{items:4}}})
$('#bags-slider').owlCarousel({loop:!0,margin:30,nav:!0,dots:!1,smartSpeed:200,responsiveClass:!0,responsive:{0:{items:1},320:{items:1},480:{items:2},640:{items:2},768:{items:2},800:{items:3},991:{items:3},1200:{items:4}}})
$('#uniform-slider').owlCarousel({loop:!0,margin:30,nav:!0,dots:!1,smartSpeed:200,responsiveClass:!0,responsive:{0:{items:1},320:{items:1},480:{items:2},640:{items:2},768:{items:2},800:{items:3},991:{items:3},1200:{items:4}}})
$('#other-products').owlCarousel({loop:!0,margin:30,nav:!0,dots:!1,smartSpeed:200,responsiveClass:!0,responsive:{0:{items:1},320:{items:1},480:{items:2},640:{items:2},768:{items:2},800:{items:3},991:{items:3},1200:{items:4}}})
$('#team-slider').owlCarousel({loop:!0,margin:30,nav:!0,dots:!1,smartSpeed:200,responsiveClass:!0,responsive:{0:{items:1},320:{items:1},480:{items:2},640:{items:2},768:{items:2},800:{items:2},960:{items:2},991:{items:2},1024:{items:3},1200:{items:3}}})
$('#testimonial-slider').owlCarousel({loop:!0,margin:30,nav:!0,dots:!1,smartSpeed:200,responsiveClass:!0,responsive:{0:{items:1},320:{items:1},480:{items:1,nav:!1},640:{items:2},768:{items:2},800:{items:2},960:{items:2},991:{items:2},1024:{items:3},1200:{items:3}}})
$("#product-tumbnail-slider").owlCarousel({loop:!0,autoplay:!0,items:1,nav:!0,autoplayHoverPause:!0,animateOut:'slideOutUp',animateIn:'slideInUp',dots:!1,});$('#team-slider-thumnail').owlCarousel({loop:!0,margin:30,nav:!0,dots:!1,smartSpeed:200,responsiveClass:!0,responsive:{0:{items:1},320:{items:1},480:{items:3},640:{items:3},768:{items:2},800:{items:3},960:{items:3},1200:{items:4}}})
try{$('#tc-counters').appear(function(){setTimeout(function(){odometer1.innerHTML=20000},0);setTimeout(function(){odometer2.innerHTML=2000},0);setTimeout(function(){odometer3.innerHTML=160},0);setTimeout(function(){odometer4.innerHTML=100},0)})}catch(err){}
$("#location-map").gmap3({marker:{address:"Haltern am See, Weseler Str. 151"},map:{options:{zoom:16,scrollwheel:!1,}},});$("#contact-map").gmap3({marker:{address:"Haltern am See, Weseler Str. 151"},map:{options:{zoom:16,scrollwheel:!1,}},});$(".panel-heading").addClass("collapsed");$("a[data-rel]").each(function(){$(this).attr("rel",$(this).data("rel"))});$("a[data-rel^='prettyPhoto']").prettyPhoto({animation_speed:'normal',slideshow:1000,autoplay_slideshow:!1,social_tools:!1});$(".youtube").each(function(){$(this).css('background-image',+this.id+'/sddefault.jpg)');$(this).append($('<div/>',{'class':'play'}));$(document).delegate('#'+this.id,'click',function(){var iframe_url="https://www.youtube.com/embed/"+this.id+"?autoplay=1&autohide=1";if($(this).data('params'))iframe_url+='&'+$(this).data('params');var iframe=$('<iframe/>',{'frameborder':'0','src':iframe_url,'width':$(this).width(),'height':$(this).height()})
$(this).replaceWith(iframe)})});var $container=$('.gallery-masonry');var $optionSets=$('.option-set');var $optionLinks=$optionSets.find('a');function doIsotopeFilter(){if($().isotope){var isotopeFilter='';$optionLinks.each(function(){var selector=$(this).attr('data-filter');var link=window.location.href;var firstIndex=link.indexOf('filter=');if(firstIndex>0){var id=link.substring(firstIndex+7,link.length);if('.'+id==selector){isotopeFilter='.'+id}}});$container.isotope({itemSelector:'.masonry-grid',filter:isotopeFilter,layoutMode:'fitRows'});$optionLinks.each(function(){var $this=$(this);var selector=$this.attr('data-filter');if(selector==isotopeFilter){if(!$this.hasClass('selected')){var $optionSet=$this.parents('.option-set');$optionSet.find('.selected').removeClass('selected');$this.addClass('selected')}}});$optionLinks.on('click',function(){var $this=$(this);var selector=$this.attr('data-filter');$container.isotope({itemSelector:'.masonry-grid',filter:selector});if(!$this.hasClass('selected')){var $optionSet=$this.parents('.option-set');$optionSet.find('.selected').removeClass('selected');$this.addClass('selected')}
return!1})}}
var isotopeTimer=window.setTimeout(function(){window.clearTimeout(isotopeTimer);doIsotopeFilter()},1000)})